version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: my_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letpass  # Ajout d'un espace après le `:`
      MYSQL_DATABASE: parrainage
      MYSQL_USER: admin
      MYSQL_PASSWORD: letpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: